### ISSUE TITLE
Implement RFC8078 section 3.4 ("accept with challenge")

### ISSUE THREAD

**Issue by johanix** [johanix/tdns#69]
The idea is that in response to the key upload the parent issues a challenge to the child: "publish this RR in the child zone to prove you are the operator". 

If it is possible to transport the challenge inside an EDE then this would be a much simpler solution than RFC 8078 section 3.3 and suits TDNS rather well, as it already has functionality for modifying the published zone.

**Comment by berrabou** [comment]
Wont fix
